[package]
name = "slides"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_matches = "1.5"
lazy_static = "1.4.0"
num_enum = "0.5"
once_cell = "1.17.0"
