[package]
name = "reaktor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slides = { path = "../slides" }
clap = {version = "2.34", features = ["yaml", "wrap_help"]}